### ISSUE TITLE
Resume gradient

### ISSUE THREAD

**Issue by iambenmitchell** [rwbutler/AnimatedGradientView#15]
Hi, how do I resume the gradient on `viewWillAppear` after the app has been in the background? Right now I just recall the gradient function which restarts it from the start. Is there a way to pick up where it was left off?

Also, when iPads rotate they leave a massive gap on the side, I have tried calling a `.setNeedsDisplay()` and `self.view.setNeedsLayout()` but neither fix the issue

Using the latest version, installed with swift package manager.

**Comment by rwbutler** [comment]
@MrBenFTW Release 3.1.0 adds the functions `pauseAnimating` and `resumeAnimating` which do what you want. However if `autoAnimate` is enabled (as is the default) then the gradient animation should now resume automatically.

The gap on the side doesn't sound related to AnimatedGradientView but rather that the view is constrained to the safe area rather than to the edges of the superview. Hope this helps.
